### ISSUE TITLE
Implement a lexer, parser and interpreter.

### ISSUE THREAD

**Issue by cyanidee** [otvv/r-lang#1]
Currently, the language is basically parsing (you can't even call that parsing at this point, though...) the source file by looking for keywords and blindly trying to match the rest of input hoping for the best.
Instead you should take your time to write an actual lexer (or tokenizer, the naming is up to you), parser and an interpreter.

- Lexer's job is to lex the source file, lex means split it up in small lexemes, or tokens, and assign them location info, like line number, column number. You should also assign them some additional info regarding what they actually are, like a string literal, number literal, identifier, opening brace etc...
- Parser's job is to process the lexemes from previous step and produce an AST (abstract syntax tree), which is simply a tree representation of your program. This step includes semantic analysis, defining the operator precedence (for example, `=` comes before any binary operator, so statements like `foo = 2 + 2` get interpreted as "assign 2 + 2 to `foo`" instead of "assign 2 to `foo` and add 2 to the result"). This is, as I experienced already, the most tedious and annoying part of writing an interpreter or a compiler. In the end your parser should be capable of outputting a usable AST that can be later easily translated back into usable source code.
- Interpreter's job is to take the resulting AST and basically execute the source code we lexed in the first pass. It's the easiest part of the whole thing, though it can be sometimes awful when it comes to dealing with UB (undefined behavior) in your language. For example, should you allow value-less variables? Should you error out in that case? What should your interpreter do in case of non-existent variable?

Before doing all of that though, I would suggest writing down an exhaustive and accurate language definition. It will (possibly) speed up and ease the development process, as you will know what to expect from the code. Defining language grammar is also a useful thing. The most important stuff is to define what (in your language) is going to be an expression, how are statements delimited, precedence of operators (I suggest you to split them up in 4-5 levels of precedence, where 4 (or 5) is the lowest, like literals, and 1 is the highest like assignment).

**Comment by cristeigabriel** [comment]
Hello cyanidee, thank you for this! I and Floody wrote the actual version of r-lang to be a parsing hybrid which is mostly scripting aimed.This project was written with no experience in language design by 2 stundents, so it is kind of hard to provide a high level standard upfront. Hopefully our current hybrid won't set your opinion in the language as a whole. We will update the language as it is and once we have a solid lang system we will push a revamp for handling the syntax as a whole. If you look towards contributing, we always appreciate pull requests.Thank you and have my kindest regards.
